# Deploy MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: redis:3.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379

---

#Service Cache
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app: cache
  ports:
  - port: 6379

--- 

#Deployment Api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: fabioleitedev/rickandmortyapichallenge:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env: 
          - name: REDIS_HOST
            value: cache
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PERSISTENCE_PERIOD_IN_DAYS
            value: "90"
          - name: CHARACTERS_API_BASE_URL
            value: https://rickandmortyapi.com/api/character

---

#Service Api
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 5000 #porta para fora
      targetPort: 5000 #porta interna do pod do app definida acima no deployment
  