version: '3'

services:
  cache:
    image: redis:3.0
    container_name: cache
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ../_data/redis-dis:/data

